# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: aleksandrreva-eng.llm-test-bench
PackageVersion: 1.0.0
InstallerType: wix
Scope: user
ReleaseDate: 2026-09-29
ProductCode: '{C6400931-BC80-4D9D-9CC4-8EF5DD6D331E}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/aleksandrreva-eng/llm-test-bench/releases/download/v1.0.0/LLMTestBench-1.0.0.msi
  InstallerSha256: F2727924C77D44CC79431CEDF1B03A5649E0293F2E8F73D94C108B611ADFF0BD
ManifestType: installer
ManifestVersion: 1.12.0
